apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-normal-load.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-exporter
  name: mysql_exporter
spec:
  ports:
    - name: "9104"
      port: 9104
      targetPort: 9104
  selector:
    io.kompose.service: mysql-exporter
status:
  loadBalancer: {}
