apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-normal-load.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-database
  name: mysql-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-normal-load.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/mysql_db_nodejs_network: "true"
        io.kompose.network/mysqlexporter_net: "true"
        io.kompose.service: mysql-database
    spec:
      containers:
        - args:
            - mysqld
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: winterstoredb
            - name: MYSQL_INIT_CONNECT
              value: SET GLOBAL skip_name_resolve = OFF;
            - name: MYSQL_PASSWORD
              value: letmein
            - name: MYSQL_ROOT_PASSWORD
              value: letmeinout
            - name: MYSQL_USER
              value: admin
            - name: SERVICE_NAME
              value: mysqldb
            - name: SERVICE_TAGS
              value: prod
            - name: TZ
              value: Asia/Singapore
          image: mysql/mysql-server
          name: mysql-server
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "1"
              memory: "536870912"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/0_init.sql
              name: mysql-database-claim0
            - mountPath: /var/lib/mysql
              name: mysql-database-claim1
            - mountPath: /etc/my.cnf
              name: mysql-database-claim2
      restartPolicy: Always
      volumes:
        - name: mysql-database-claim0
          persistentVolumeClaim:
            claimName: mysql-database-claim0
        - name: mysql-database-claim1
          persistentVolumeClaim:
            claimName: mysql-database-claim1
        - name: mysql-database-claim2
          persistentVolumeClaim:
            claimName: mysql-database-claim2
status: {}
