apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-normal-load.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-exporter1
  name: nginx-exporter1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-exporter1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-normal-load.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/nginx_exporter_net: "true"
        io.kompose.network/prometheus_collection_network: "true"
        io.kompose.service: nginx-exporter1
    spec:
      containers:
        - args:
            - -nginx.scrape-uri
            - http://nginx_webserver1:7071/metrics
          env:
            - name: TZ
              value: Asia/Singapore
          image: nginx/nginx-prometheus-exporter:0.10.0
          name: nginx-exporter1
          ports:
            - containerPort: 9113
          resources: {}
      restartPolicy: Always
status: {}
