apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-normal-load.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-exporter2
  name: nginx-exporter2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-exporter2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-normal-load.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/nginx_exporter_net: "true"
        io.kompose.network/prometheus_collection_network: "true"
        io.kompose.service: nginx-exporter2
    spec:
      containers:
        - args:
            - -nginx.scrape-uri
            - http://nginx_webserver2:7072/metrics
          env:
            - name: TZ
              value: Asia/Singapore
          image: nginx/nginx-prometheus-exporter:0.10.0
          name: nginx-exporter2
          ports:
            - containerPort: 9113
            - containerPort: 9115
          resources: {}
      restartPolicy: Always
status: {}
