apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-normal-load.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-web-server2
  name: nginx-web-server2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-web-server2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-normal-load.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/nginx_exporter_net: "true"
        io.kompose.network/nginx_lb_webserver_network: "true"
        io.kompose.network/nginx_web_server_nodejs_network: "true"
        io.kompose.network/telegraf_nginx_network: "true"
        io.kompose.service: nginx-web-server2
    spec:
      containers:
        - image: nginx_ssl
          name: nginx-webserver2
          ports:
            - containerPort: 8080
            - containerPort: 7072
          resources:
            limits:
              cpu: 250m
              memory: "10485760"
          volumeMounts:
            - mountPath: /var/www/localhost/htdocs
              name: nginx-web-server2-claim0
            - mountPath: /etc/nginx/http.d
              name: nginx-web-server2-claim1
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-web-server2-claim2
            - mountPath: /var/log/nginx
              name: nginx-web-server2-claim3
      restartPolicy: Always
      volumes:
        - name: nginx-web-server2-claim0
          persistentVolumeClaim:
            claimName: nginx-web-server2-claim0
        - name: nginx-web-server2-claim1
          persistentVolumeClaim:
            claimName: nginx-web-server2-claim1
        - name: nginx-web-server2-claim2
          persistentVolumeClaim:
            claimName: nginx-web-server2-claim2
        - name: nginx-web-server2-claim3
          persistentVolumeClaim:
            claimName: nginx-web-server2-claim3
status: {}
