apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-normal-load.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-exporter1
  name: nginx-exporter1
spec:
  ports:
    - name: "9113"
      port: 9113
      targetPort: 9113
    - name: 9113-tcp
      port: 9113
      targetPort: 9113
  selector:
    io.kompose.service: nginx-exporter1
status:
  loadBalancer: {}
