apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-normal-load.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-exporter2
  name: nginx-exporter2
spec:
  ports:
    - name: "9115"
      port: 9115
      targetPort: 9113
    - name: 9115-tcp
      port: 9115
      targetPort: 9115
  selector:
    io.kompose.service: nginx-exporter2
status:
  loadBalancer: {}
