apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-normal-load.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs-app1
  name: nodejs_app1
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: 8888-tcp
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: nodejs-app1
status:
  loadBalancer: {}
